export const mock = [
    {
        id: 0,
        title: 'Вино белое сухое «Alla Moda Pinot Grigio delle Venezie»',
        image: 'https://static.winestreet.ru/off-line/goods_file/160040/file_small.jpg',
        type: 'Белое, Сухое',
        year: '2021 г.',
        sort: 'Пино Гриджио (100%)',
        brand: 'Alla Moda',
        region: 'Италия, Венето, Венеция',
        strength: '12,5%',
    },
    {
        id: 1,
        title: 'Вино красное сухое «Barkan Carignan Monfort»',
        image: 'https://static.winestreet.ru/off-line/goods_file/152417/file_small.jpg',
        type: 'Красное, Сухое',
        year: '2019 г.',
        sort: 'Кариньяно (100%)',
        brand: 'Barkan',
        region: 'Израиль, Галилея',
        strength: '11,5%',
    },
    {
        id: 2,
        title: 'Вино красное сухое «Antano Tinto»',
        image: 'https://static.winestreet.ru/off-line/goods_file/206276/file_small.jpg',
        type: 'Красное, Сухое',
        year: '2019 г.',
        sort: 'Темпранильо (100%)',
        brand: 'Garcia Carrion',
        region: 'Испания, Риоха',
        strength: '13%',
    },
    {
        id: 3,
        title: 'Вино белое сухое «Russian Jack Sauvignon Blanc»',
        image: 'https://static.winestreet.ru/off-line/goods_file/168287/file_small.jpg',
        type: 'Белое, Сухое',
        year: '2020 г.',
        sort: 'Совиньон Блан',
        brand: 'Russian Jack',
        region: 'Новая Зеландия, Долина Мальборо',
        strength: '13%',
    },
    {
        id: 4,
        title: 'Вино белое сухое «Gaumen Spiel Riesling»',
        image: 'https://static.winestreet.ru/off-line/goods_file/185663/file_small.jpg',
        type: 'Белое, Сухое',
        year: '2019 г.',
        sort: 'Рислинг (100%)',
        brand: 'Gaumen Spiel',
        region: 'Германия, Пфальц',
        strength: '12%',
    },
    {
        id: 5,
        title: 'Вино белое сухое «LFE Pinot Grigio Pupilla»',
        image: 'https://static.winestreet.ru/off-line/goods_file/44782/file_small.jpg',
        type: 'Белое, Сухое',
        year: '2019 г.',
        sort: 'Пино Гриджио (100%)',
        brand: 'Luis Felipe Edwards',
        region: 'Чили, Центральная долина',
        strength: '13%',
    },
    {
        id: 6,
        title: 'Вино белое сухое «Rutini Chardonnay»',
        image: 'https://static.winestreet.ru/off-line/goods_file/113606/file_small.jpg',
        type: 'Белое, Сухое',
        year: '2017 г.',
        sort: 'Шардоне (100%)',
        brand: 'Rutini',
        region: 'Аргентина, Мендоса',
        strength: '10,5%',
    },
    {
        id: 7,
        title: 'Вино белое сухое «Erbaluce di Caluso Gattinara Antoniolo»',
        image: 'https://static.winestreet.ru/off-line/goods_file/58774/file_small.jpg',
        type: 'Белое, Сухое',
        year: '2017 г.',
        sort: 'Эрбалуче (100%)',
        brand: 'Antoniolo',
        region: 'Италия, Пьемонт',
        strength: '12,5%',
    },
    {
        id: 8,
        title: 'Вино красное сухое «Luis Felipe Edwards Cabernet Sauvignon Reserva»',
        image: 'https://static.winestreet.ru/off-line/goods_file/115577/file_small.jpg',
        type: 'Красное, Сухое',
        year: '2019 г.',
        sort: 'Каберне Совиньон (90%), Карменере (5%), Шираз (Сира) (5%)',
        brand: 'Luis Felipe Edwards',
        region: 'Чили, Кольчагуа, Центральная долина',
        strength: '14%',
    },
    {
        id: 9,
        title: 'Вино белое сухое «Leyda Sauvignon Blanc Reserva»',
        image: 'https://static.winestreet.ru/off-line/goods_file/169181/file_small.jpg',
        type: 'Белое, Сухое',
        year: '2020 г.',
        sort: 'Совиньон Блан (100%)',
        brand: 'Leyda',
        region: 'Чили, Аконкагуа, Долина Лейда',
        strength: '13%',
    },
    {
        id: 10,
        title: 'Вино белое сухое «Contini Pariglia Vermentino di Sardegna»',
        image: 'https://static.winestreet.ru/off-line/goods_file/113540/file_small.jpg',
        type: 'Белое, Сухое',
        year: '2019 г.',
        sort: 'Верментино (100%)',
        brand: 'Contini',
        region: 'Италия, Сардиния',
        strength: '13,5%',
    },
    {
        id: 11,
        title: 'Вино красное сухое «Minini Cabernet»',
        image: 'https://static.winestreet.ru/off-line/goods_file/115277/file_small.jpg',
        type: 'Красное, Сухое',
        year: '2018 г.',
        sort: 'Каберне Совиньон (100%)',
        brand: 'Minini',
        region: 'Италия, Венето',
        strength: '12%',
    },
    {
        id: 12,
        title: 'Вино белое сухое «Borgo dei Mori Pinot Grigio delle Venezie»',
        image: 'https://static.winestreet.ru/off-line/goods_file/132416/file_small.jpg',
        type: 'Белое, Сухое',
        year: '2019 г.',
        sort: 'Пино Гриджио (100%)',
        brand: 'Borgo Dei Mori',
        region: 'Италия, Венето, Венеция',
        strength: '12,5%',
    },
    {
        id: 13,
        title: 'Вино белое сухое «Gross Welschriesling PRO»',
        image: 'https://static.winestreet.ru/off-line/goods_file/199247/file_small.jpg',
        type: 'Белое, Сухое',
        year: '2020 г.',
        sort: 'Вельшрислинг (100%)',
        brand: 'Gross',
        region: 'Австрия, Штирия',
        strength: '11,5%',
    },
    {
        id: 14,
        title: 'Вино красное сухое «Famille Bougrier Confidences Chinon»',
        image: 'https://static.winestreet.ru/off-line/goods_file/168020/file_small.jpg',
        type: 'Красное, Сухое',
        year: '2020 г.',
        sort: 'Каберне Фран (100%)',
        brand: 'Famille Bougrier',
        region: 'Франция, Долина Луары, Шинон',
        strength: '13%',
    },
    {
        id: 15,
        title: "Вино красное сухое «Fondo Antico Nene Nero d'Avola»",
        image: 'https://static.winestreet.ru/off-line/goods_file/155204/file_small.jpg',
        type: 'Красное, Сухое',
        year: '2019 г.',
        sort: "Неро Д'Аволо (100%)",
        brand: 'Fondo Antico',
        region: 'Италия, Сицилия',
        strength: '14%',
    },
    {
        id: 16,
        title: 'Вино крепленое ликерное белое сладкое «Мускат белый Красного камня»',
        image: 'https://static.winestreet.ru/off-line/goods_file/137309/file_small.jpg',
        type: 'Белое, Сладкое',
        year: '2020 г.',
        sort: 'Мускат',
        brand: 'Массандра',
        region: 'Россия',
        strength: '13%',
    },
    {
        id: 17,
        title: 'Вино белое сухое «Weisser Schiefer “S”»',
        image: 'https://static.winestreet.ru/off-line/goods_file/137159/file_small.jpg',
        type: 'Белое, Сухое',
        year: '2017 г.',
        sort: 'Вельшрислинг, Грюнер Велтлинер, Пино Блан',
        brand: 'Uwe Schiefer',
        region: 'Австрия, Бургенланд',
        strength: '13%',
    },
    {
        id: 18,
        title: 'Вино белое полусухое «Domaine Weinbach Muscat»',
        image: 'https://static.winestreet.ru/off-line/goods_file/75096/file_small.jpg',
        type: 'Белое, Полусухое',
        year: '2018 г.',
        sort: 'Мускат Оттонель (70%), Мускат Эльзасский (30%)',
        brand: 'Domaine Weinbach',
        region: 'Франция, Эльзас',
        strength: '13%',
    },
    {
        id: 19,
        title: 'Вино белое сухое «Les Clos Chablis Grand Cru АОС Maison Olivier Tricon»',
        image: 'https://static.winestreet.ru/off-line/goods_file/158555/file_small.jpg',
        type: 'Белое, Сухое',
        year: '2011 г.',
        sort: 'Шардоне (100%)',
        brand: 'Olivier Tricon',
        region: 'Франция, Бургундия, Шабли',
        strength: '13%',
    },
    {
        id: 20,
        title: "Вино белое сухое «Ca' Marcanda Vistamare»",
        image: 'https://static.winestreet.ru/off-line/goods_file/63478/file_small.jpg',
        type: 'Белое, Сухое',
        year: '2017 г.',
        sort: 'Верментино (40%), Вионье (40%), Фиано (20%)',
        brand: 'Ca Marcanda',
        region: 'Италия, Тоскана',
        strength: '13,5%',
    },
    {
        id: 21,
        title: 'Вино розовое сладкое «Массандра Мускат Розовый Южнобережный»',
        image: 'https://static.winestreet.ru/off-line/goods_file/144215/file_small.jpg',
        type: 'Розовое, Сладкое',
        year: '2018 г.',
        sort: 'Мускат',
        brand: 'Массандра',
        region: 'Россия',
        strength: '16%',
    },
    {
        id: 22,
        title: 'Вино розовое полусухое «Cielo e Terra Pinot Grigio Blush»',
        image: 'https://static.winestreet.ru/off-line/goods_file/27164/file_small.jpg',
        type: 'Розовое, Полусухое',
        year: '2018 г.',
        sort: 'Пино Гриджио (100%)',
        brand: 'Cielo e Terra',
        region: 'Италия, Венето, Венеция',
        strength: '12%',
    },
];
